# 희귀 드롭 알림 설정
# 확률 범위는 0~1 사이 (예: 0.1 = 10%, 0.001 = 0.1%)
# {item}, {amount}, {chance}, {player}, {magicfind} 플레이스홀더 사용 가능

# 블랙리스트 - 희귀 드롭 알림을 표시하지 않을 아이템/드롭테이블
blacklist:
  items:
    - "슬픔의잔재"
    - "볼타"
    - "플라즈마"
  droptables:
    - "기본몹드롭"
    - "디멘션드롭"
    - "슬레이어_파우더"
    - "슬레이어_파우더_6티어"
    - "슬레이어_크레용"
    - "필드_파우더"
    - "레이드_파우더"
    - "레이드_크레용"
    - "룬던전드롭"
    - "포스카인드"
    - "전자적해괴함"
    - "만유의시선"
    - "치아"
    - "포기한것"
    - "파란고래"
    - "널템"
    - "세피로트드롭"
    - "클리포트드롭"

rare_drops:
  occasional:
    enabled: true
    min_chance: 0.10      # 10%
    max_chance: 0.20      # 20%
    message: "&9Occasional DROP! {item} &ex{amount} &7[ &f{chance} &7] &3[ &b신비의 추적 +{magicfind} &3]"
    sound: "slayerdrop.occasional_drop"
    volume: 1.0
    pitch: 1.0
    broadcast: false      # false = 띄운 플레이어만, true = 전체 공지

  rare:
    enabled: true
    min_chance: 0.02      # 2%
    max_chance: 0.10      # 10%
    message: "&5Rare DROP! {item} &ex{amount} &7[ &f{chance} &7] &3[ &b신비의 추적 +{magicfind} &3]"
    sound: "slayerdrop.occasional_drop"
    volume: 1.0
    pitch: 1.0
    broadcast: false

  extraordinary:
    enabled: true
    min_chance: 0.001     # 0.1%
    max_chance: 0.02      # 2%
    message: "&6Extraordinary DROP! {item} &ex{amount} &7[ &f{chance} &7] &3[ &b신비의 추적 +{magicfind} &3]"
    sound: "slayerdrop.rare_drop"
    volume: 1.0
    pitch: 1.0
    broadcast: false

  pray_rngesus:
    enabled: true
    min_chance: 0.0002    # 0.02%
    max_chance: 0.001     # 0.1%
    message: "&dPray RNGesus DROP! {item} &ex{amount} &7[ &f{chance} &7] &3[ &b신비의 추적 +{magicfind} &3] &f- &f&l{player}"
    sound: "slayerdrop.pray_rngesus_drop"
    volume: 1.0
    pitch: 1.0
    broadcast: true

  rngesus_incarnate:
    enabled: true
    min_chance: 0.00005   # 0.005%
    max_chance: 0.0002    # 0.02%
    message: "&cRNGesus Incarnate DROP! {item} &ex{amount} &7[ &f{chance} &7] &3[ &b신비의 추적 +{magicfind} &3] &f- &f&l{player}"
    sound: "slayerdrop.pray_rngesus_drop"
    volume: 1.0
    pitch: 1.0
    broadcast: true

  rngesus_insane:
    enabled: true
    min_chance: 0.000005  # 0.0005%
    max_chance: 0.00005   # 0.005%
    message: "&4RNGesus Insane DROP! {item} &ex{amount} &7[ &f{chance} &7] &3[ &b신비의 추적 +{magicfind} &3] &f- &f&l{player}"
    sound: "slayerdrop.rngesus_incarnate_drop"
    volume: 1.0
    pitch: 1.0
    broadcast: true

  rngesus_unleashed:
    enabled: true
    min_chance: 0.0       # 0%
    max_chance: 0.000005  # 0.0005%
    message: "&5&lRNGesus Unleashed DROP! &r{item} &ex{amount} &7[ &f{chance} &7] &3[ &b신비의 추적 +{magicfind} &3] &f- &f&l{player}"
    sound: "slayerdrop.rngesus_incarnate_drop"
    volume: 1.0
    pitch: 1.0
    broadcast: true

# 사운드 대체 설정 (커스텀 사운드가 없을 때 사용할 바닐라 사운드)
fallback_sounds:
  occasional: "ENTITY_EXPERIENCE_ORB_PICKUP"
  rare: "ENTITY_PLAYER_LEVELUP"
  incarnate: "ENTITY_ENDER_DRAGON_GROWL"